/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntornoGrafico;

import Xogo.Xogo;
import java.awt.Color;

/**
 *
 * @author Carlos
 */
public class TaboleiroGrafico extends javax.swing.JFrame {
    Boton[][] botons= new Boton[8][8];
    /**
     * Creates new form Taboleiro
     */
    public TaboleiroGrafico() {
        initComponents();
        this.encherBotons();
        this.pintarBotons();
        this.refrescar();
    }
    
    public void encherBotons(){
        for(int c=0; c<botons.length; c++){
            for(int f=0;f<botons.length;f++){
                botons[c][f]= new Boton(75*c,75*f,75,75);
                botons[c][f].setName(c, f);
                PanelTab.add(botons[c][f]);
                
            }
            
        }
    }
    
    private void pintarBotons(){
        int x,y;
        for(x=0;x<botons.length;x++){
            for(y=0;y<botons.length;y++){
                if(y%2==0 && x%2==0 || y%2!=0 && x%2!=0){
                    botons[x][y].setBackground(Color.BLACK);
                }else{
                    botons[x][y].setBackground(Color.WHITE);
                }
            }
        }
    }
    
    //Proba
    public void refrescar(){
        int x,y;
        for(x=0;x<botons.length;x++){
            for(y=0;y<botons.length;y++){
                try{
                    if(Xogo.tab.get(x, y).getPropiedadeDe()==Xogo.getXog1())
                        botons[x][y].setIcon(Xogo.tab.get(x, y).getIconaxog1());
                    else if(Xogo.tab.get(x, y).getPropiedadeDe()==Xogo.getXog2())
                        botons[x][y].setIcon(Xogo.tab.get(x, y).getIconaxog2());
                }catch(NullPointerException e){
                    
                }
            }
        }
    }
    //Proba

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTab = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Carlos\\Desktop\\Pezas Xadrez\\AlfilBranco.png")); // NOI18N
        jButton1.setText("jButton1");

        javax.swing.GroupLayout PanelTabLayout = new javax.swing.GroupLayout(PanelTab);
        PanelTab.setLayout(PanelTabLayout);
        PanelTabLayout.setHorizontalGroup(
            PanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTabLayout.createSequentialGroup()
                .addContainerGap(816, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        PanelTabLayout.setVerticalGroup(
            PanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTabLayout.createSequentialGroup()
                .addContainerGap(729, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaboleiroGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaboleiroGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaboleiroGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaboleiroGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaboleiroGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTab;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
